export const REQUEST_SUGGESTIONS = 'REQUEST_SUGGESTIONS';
export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';
export const SAVE_SUGGESTION = 'SAVE_SUGGESTION';
export const SELECT_PLACE = 'SELECT_PLACE';
export const RECEIVE_PLACE_DATA = 'RECEIVE_PLACE_DATA';
